name: LuxPower Auto Schedule

on:
  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:
    inputs:
      action:
        description: 'Chon hanh dong'
        required: true
        default: 'enable'
        type: choice
        options:
          - enable
          - disable

jobs:
  control:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm install axios axios-cookiejar-support tough-cookie

      - name: Determine Action
        run: |
          echo "======================================"
          echo "EVENT: ${{ github.event_name }}"
          echo "SCHEDULE: ${{ github.event.schedule }}"
          echo "======================================"

          VN_TIME=$(TZ='Asia/Ho_Chi_Minh' date '+%Y-%m-%d %H:%M:%S')

          echo "Gio Viet Nam: $VN_TIME"

          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then

            ACTION="${{ inputs.action }}"

            echo "Chay thu cong"
            echo "ACTION=$ACTION"

          else

            CURRENT_HOUR=$(TZ='Asia/Ho_Chi_Minh' date '+%H')
            CURRENT_MINUTE=$(TZ='Asia/Ho_Chi_Minh' date '+%M')

            echo "Gio VN: $CURRENT_HOUR:$CURRENT_MINUTE"

            # TEST:
            # Truoc 10:00 -> disable
            # Tu 10:00 tro di -> enable

            if [ "$CURRENT_HOUR" -lt 10 ]; then
              ACTION="disable"
            else
              ACTION="enable"
            fi

            echo "Chay tu dong"
            echo "ACTION=$ACTION"

          fi

          echo "ACTION=$ACTION" >> "$GITHUB_ENV"

      - name: Run LuxPower Control
        env:
          LUX_ACCOUNT: ${{ secrets.LUX_ACCOUNT }}
          LUX_PASSWORD: ${{ secrets.LUX_PASSWORD }}
          INVERTER_SN: ${{ secrets.INVERTER_SN }}
        run: |
          echo "======================================"
          echo "LUXPOWER CONTROL"
          echo "ACTION=$ACTION"
          echo "INVERTER_SN=$INVERTER_SN"
          echo "======================================"

          node luxpower.js "$ACTION"
