name: LuxPower Auto Schedule

on:
  schedule:
    # 08:00 Viet Nam = 01:00 UTC
    - cron: '0 1 * * *'

    # 11:24 Viet Nam = 04:24 UTC
    - cron: '24 4 * * *'

  workflow_dispatch:
    inputs:
      action:
        description: 'Chon hanh dong'
        required: true
        default: 'enable'
        type: choice
        options:
          - enable
          - disable

jobs:
  control:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm install axios axios-cookiejar-support tough-cookie

      - name: Determine Action
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "ACTION=${{ inputs.action }}" >> "$GITHUB_ENV"
            echo "Workflow thu cong"
            echo "ACTION=${{ inputs.action }}"
          else
            # GitHub Actions cron dung UTC
            # 01:00 UTC = 08:00 Viet Nam -> DISABLE
            # 04:24 UTC = 11:24 Viet Nam -> ENABLE

            CURRENT_CRON="${{ github.event.schedule }}"

            echo "Cron hien tai: $CURRENT_CRON"

            if [ "$CURRENT_CRON" = "0 1 * * *" ]; then
              echo "ACTION=disable" >> "$GITHUB_ENV"
              echo "ACTION=disable"
              echo "Ly do: 08:00 Viet Nam"
            elif [ "$CURRENT_CRON" = "24 4 * * *" ]; then
              echo "ACTION=enable" >> "$GITHUB_ENV"
              echo "ACTION=enable"
              echo "Ly do: 11:24 Viet Nam"
            else
              echo "Khong xac dinh duoc cron."
              exit 1
            fi
          fi

      - name: Run LuxPower Control
        env:
          LUX_ACCOUNT: ${{ secrets.LUX_ACCOUNT }}
          LUX_PASSWORD: ${{ secrets.LUX_PASSWORD }}
          INVERTER_SN: ${{ secrets.INVERTER_SN }}
        run: |
          echo "======================================"
          echo "LUXPOWER AUTO CONTROL"
          echo "======================================"
          echo "ACTION=$ACTION"
          echo "INVERTER_SN=$INVERTER_SN"
          echo "======================================"

          node luxpower.js "$ACTION"
